#!/usr/bin/env bash
# The opencode installer, run for real into scratch destinations.
# Test scaffolding: the scratch directory is removed on every exit. rm -rf
# never follows a symbolic link, so fx's own skills are never touched.
set -euo pipefail
FX="$(cd "$(dirname "$0")/../.." && pwd -P)"
SCRATCH="$(mktemp -d)"
trap 'rm -rf "$SCRATCH"' EXIT
fails=0
check() { if eval "$2"; then echo "ok: $1"; else echo "FAIL: $1"; fails=$((fails + 1)); fi; }
install_into() { python3 "$FX/scripts/fx-opencode-install" --dest "$1" > "$SCRATCH/$(basename "$1").out" 2>&1; }
user_invoked() { grep -l '^disable-model-invocation: true' "$FX"/skills/*/SKILL.md | xargs -n1 dirname | xargs -n1 basename; }

# 1. another tool's skill already there, and a stale fx link
D1="$SCRATCH/d1"
mkdir -p "$D1/skills/foreign-skill"
printf -- '---\nname: foreign-skill\ndescription: not fx\n---\nforeign\n' > "$D1/skills/foreign-skill/SKILL.md"
FOREIGN_SUM="$(sha256sum "$D1/skills/foreign-skill/SKILL.md" | cut -d' ' -f1)"
ln -s "$FX/skills/fx-gone" "$D1/skills/fx-gone"
printf '{"theme": "mine"}\n' > "$D1/opencode.json"
CONFIG_SUM="$(sha256sum "$D1/opencode.json" | cut -d' ' -f1)"
install_into "$D1" || true

check "skills is a real directory" '[ -d "$D1/skills" ] && [ ! -L "$D1/skills" ]'
check "foreign skill untouched" '[ ! -L "$D1/skills/foreign-skill" ] && [ "$(sha256sum "$D1/skills/foreign-skill/SKILL.md" | cut -d" " -f1)" = "$FOREIGN_SUM" ]'
check "stale fx link removed" '[ ! -L "$D1/skills/fx-gone" ]'
check "opencode.json untouched" '[ "$(sha256sum "$D1/opencode.json" | cut -d" " -f1)" = "$CONFIG_SUM" ]'
for s in $(ls "$FX/skills"); do
  if user_invoked | grep -qx "$s"; then
    check "user-invoked $s not linked" '[ ! -e "$D1/skills/$s" ] && [ ! -L "$D1/skills/$s" ]'
  else
    check "skill $s linked" '[ -L "$D1/skills/$s" ] && [ "$(readlink "$D1/skills/$s")" = "$FX/skills/$s" ]'
  fi
done
check "references resolve through a linked skill" '[ -f "$D1/skills/fx-tdd/../../references/vocab/good-tests.md" ]'
for f in "$D1"/commands/*.md; do
  n="$(basename "$f")"
  check "$n has no template field" '! grep -q "^template:" "$f"'
  check "$n carries its prompt in the body" 'grep -qF "Arguments, if any: \$ARGUMENTS" "$f"'
done
A="$D1/commands/fx-audit.md"
check "fx-audit command generated" '[ -f "$A" ]'
check "fx-audit command has no relative paths" '! grep -qF "../../" "$A"'
check "fx-audit command names the audit template" 'grep -qF "$D1/references/audit-template.md" "$A"'
while IFS= read -r p; do
  check "fx-audit path exists: ${p#$D1/}" '[ -e "$p" ]'
done < <(grep -oE "$D1/(references|agents)/[A-Za-z0-9/._-]+" "$A" | sort -u)

# 2. a second install into the same destination changes nothing
find "$D1" -type f -o -type l | sort | while read -r f; do printf '%s %s\n' "$f" "$( [ -L "$f" ] && readlink "$f" || sha256sum "$f" | cut -d' ' -f1)"; done > "$SCRATCH/first.txt"
install_into "$D1" || true
find "$D1" -type f -o -type l | sort | while read -r f; do printf '%s %s\n' "$f" "$( [ -L "$f" ] && readlink "$f" || sha256sum "$f" | cut -d' ' -f1)"; done > "$SCRATCH/second.txt"
check "second install identical" 'diff -q "$SCRATCH/first.txt" "$SCRATCH/second.txt" >/dev/null'

# 3. an earlier install's whole-folder link becomes a folder of links
D2="$SCRATCH/d2"; mkdir -p "$D2"; ln -s "$FX/skills" "$D2/skills"
install_into "$D2" || true
check "whole-folder link replaced" '[ -d "$D2/skills" ] && [ ! -L "$D2/skills" ] && [ -L "$D2/skills/fx-tdd" ]'
check "fx skills directory intact" '[ -f "$FX/skills/fx-tdd/SKILL.md" ] && [ -f "$FX/skills/fx-audit/SKILL.md" ]'

# 4. a real entry with an fx skill's name is refused and left alone
D3="$SCRATCH/d3"; mkdir -p "$D3/skills/fx-tdd"; echo mine > "$D3/skills/fx-tdd/SKILL.md"
set +e; install_into "$D3"; rc=$?; set -e
check "same-named real entry refused" '[ "$rc" -ne 0 ] && grep -q "fx-tdd" "$SCRATCH/d3.out"'
check "same-named real entry unchanged" '[ "$(cat "$D3/skills/fx-tdd/SKILL.md")" = mine ]'

# 5. a command file another tool created, never generated by this installer,
# is refused rather than overwritten silently
D4="$SCRATCH/d4"; mkdir -p "$D4/commands"; printf 'not generated\n' > "$D4/commands/fx-critique.md"
set +e; install_into "$D4"; rc=$?; set -e
check "foreign command file refused" '[ "$rc" -ne 0 ] && grep -q "fx-critique" "$SCRATCH/d4.out"'
check "foreign command file unchanged" '[ "$(cat "$D4/commands/fx-critique.md")" = "not generated" ]'

if [ "$fails" -ne 0 ]; then echo "opencode install: $fails failed"; exit 1; fi
echo "opencode install: all passed"
